#Buttons
b1 = "SETTINGS 🛠"
b2 = "HELP 🆘"
b3 = "DOWNLOAD LIMIT 🔄"
b4 = "CONTENT FILTER 🤑"
b5 = "CONTENT TYPE 👥"
b6 = "TOP"
b7 = "NEW"
b9 = "RISING"
b10 = "HOT"
b11 = "PHOTO"
b12 = "VIDEO"
b13 = "GIF"
b14 = "ALL"
b20 = "MAIN MENU 🔙"